stages:
  - check
  - deploy

check_index:
  stage: check
  script:
    - test -f public/index.html
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  only:
    - main
